version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/numble-9

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 600
      runas: ec2-user
  ValidateService:
    - location: health.sh
      timeout: 600
      runas: ec2-user