name: Numble Project Push for CI / CD with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Make Directory for deliver
        run: mkdir deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

      - name: Copy appspec
        run: cp ./appspec.yml ./deploy/

      - name: Copy scripts
        run: cp ./scripts/* ./deploy/

      - name: Copy Dockerfile
        run: cp ./Dockerfile ./deploy/

      - name: Make zip file
        run: zip -r -qq -j ./numble-springboot-webservice.zip ./deploy

      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          ./numble-springboot-webservice.zip s3://numble-9-codedeploy/

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name numble-9-codedeploy \
          --deployment-group-name numble-9-github-action \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=numble-9-codedeploy,bundleType=zip,key=numble-springboot-webservice.zip \
          --region ap-northeast-2